Create Accessibility Avery
CivicActions/accessibility pull request #238
Opened 2021-04-08 22:49 UTC by mikang

2021-04-08 22:54 UTC, dmundra requested changes
@mikang missing .md for and headers for this one as well. Similar to #237

2021-04-13 22:49 UTC, mikang commented
I've made the changes @dmundra - does it notify you now to merge? Is there another action I should take?

2021-04-13 22:49 UTC, dmundra commented on Personas/accessibility-avery.md
> +# Description
@mikang I think these and below headers should be second-level so `##`

2021-04-13 22:52 UTC, dmundra commented
> I've made the changes @dmundra - does it notify you now to merge? Is there another action I should take?

@mikang it does. I did notice a minor issue with headers. I think the rest of the headers after the first one should be second-level.

2021-04-13 23:03 UTC, mikang commented
@dmundra nice! both on the notifications and the change request. I've made the update with the ##s.

2021-04-13 23:04 UTC, dmundra approved these changes

2021-04-13 23:04 UTC, merged

2021-04-13 23:05 UTC, dmundra commented
Looking good @mikang. Pa11y-ci had a crash, you can just manually merge it.